### ISSUE TITLE
ER図作成

### ISSUE THREAD

**Issue by watanabe0055** [the-hack-community/teamdev-2023-jan-team1#18]
![スクリーンショット 2023-01-20 22 43 32](https://user-images.githubusercontent.com/103058543/213710152-cfcdd35f-2165-4efc-8949-bb114cd2f128.png)
https://drive.google.com/file/d/1hdLAX01u49gSRw8R-B9ysvN4Ji6QWr0p/view

**Comment by watanabe0055** [comment]
Articles
・アプリの根幹なので、必須でいいと思います
　- titleを必須
　- contentを必須

Categories
・ユーザーがカラム作成するわけじゃないと思うけど、nameだけとかはないと思うので、必須でいい気がします
　- name
　- color

Users
本当はもっとカラムある気がするけど、gem入れてからer図追加する感じですか？

**Comment by funxxfun** [comment]
> Articlesーtitle、contentを必須
> Categoriesーname、colorを必須

→OK
Not Nullとしてpresence: trueでのバリデーションかけておきます。

> Users
> 本当はもっとカラムある気がするけど、gem入れてからer図追加する感じです？

→deviseが自動作成されるものはカラムにせず、実際に入力などをこおなうために扱うカラムしか記載しませんでした。
他に何か必要そうなものがあればGem入れる前でもER追加するので教えてください！

**Comment by funxxfun** [comment]
categoriesテーブルのcreateed_at、updated_atは抜けていたので追記しています。

**Comment by rdon-key** [comment]
>・アプリの根幹なので、必須でいいと思います

破綻するわけではないのでモデルでの制約は行わずAPIのバリデーションだけでもいいと思いますがどうですかね？

**Comment by funxxfun** [comment]
[Not Null制約とmodelのバリデーション(presence: true)の違い](https://qiita.com/HIROKOBA/items/eff728c91860cd95baba) 

どんな差が出るのかよくわかっていなかったので、この記事参考にNot Null制約のみつけようかな〜と思っていますが、あるどんさんのご指摘と合致しますかね？？

**Comment by honda0924** [comment]
両方つけた方がいいと思います。
modelでバリデーションつけないとrspec通ってしまうと思います。

**Comment by funxxfun** [comment]
了解しました！

> Not Nullとしてpresence: trueでのバリデーションかけておきます。

最初のこのパターンで行きたいと思います。

**Comment by funxxfun** [comment]
現時点での訂正完了したためクローズします
